/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.application.form.other;

import Repository.ThongKeHDResponsitory;
import Utils.XuLyString;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tabah
 */
public class Form_ThongKe extends javax.swing.JPanel {

    private ThongKeHDResponsitory thongke = new ThongKeHDResponsitory();

    /**
     * Creates new form Form_ThongKe
     */

    public Form_ThongKe() {
        initComponents();
        inits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_nhanvien = new javax.swing.JTable();
        panel_doanhthu = new javax.swing.JPanel();
        lbl_doanhthu = new javax.swing.JLabel();
        lbl_showdoanhthutoday = new javax.swing.JLabel();
        lbl_hoadon = new javax.swing.JLabel();
        lbl_showhoadontoday = new javax.swing.JLabel();
        lbl_khachhang = new javax.swing.JLabel();
        lbl_shownewkhachhangtoday = new javax.swing.JLabel();
        lbl_hoadon1 = new javax.swing.JLabel();
        lbl_countsanphamtoday = new javax.swing.JLabel();
        panel_doanhthu1 = new javax.swing.JPanel();
        lbl_doanhthu1 = new javax.swing.JLabel();
        lbl_showdoanhthuthismonth = new javax.swing.JLabel();
        lbl_hoadon2 = new javax.swing.JLabel();
        lbl_showhoadonthismonth = new javax.swing.JLabel();
        lbl_khachhang1 = new javax.swing.JLabel();
        lbl_shownewkhachhangthismonth = new javax.swing.JLabel();
        lbl_hoadon3 = new javax.swing.JLabel();
        lbl_countsanphamthismonth = new javax.swing.JLabel();
        btn_openchart = new javax.swing.JButton();
        panel_lshd = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_hoadon = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        datestart = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        dateend = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_nhanvien1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_khachhang = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOP 5 Nhân Viên Doanh Số Cao Nhất Tháng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbl_nhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã Nhân Viên", "Họ Và Tên", "Doanh Số"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_nhanvien);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel_doanhthu.setBackground(new java.awt.Color(204, 204, 255));
        panel_doanhthu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doanh Thu Hôm Nay", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 51, 51))); // NOI18N

        lbl_doanhthu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_doanhthu.setForeground(new java.awt.Color(255, 255, 255));
        lbl_doanhthu.setText("Doanh Thu Hôm Nay");

        lbl_showdoanhthutoday.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_showdoanhthutoday.setText("1,300,000 VNĐ");

        lbl_hoadon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_hoadon.setForeground(new java.awt.Color(255, 255, 255));
        lbl_hoadon.setText("Số Hóa Đơn");

        lbl_showhoadontoday.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_showhoadontoday.setText("10");

        lbl_khachhang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_khachhang.setForeground(new java.awt.Color(255, 255, 255));
        lbl_khachhang.setText("Số Khách Hàng Mới");

        lbl_shownewkhachhangtoday.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_shownewkhachhangtoday.setText("10");

        lbl_hoadon1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_hoadon1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_hoadon1.setText("Số Lượng Sản Phẩm Bán Ra");

        lbl_countsanphamtoday.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_countsanphamtoday.setText("10");

        javax.swing.GroupLayout panel_doanhthuLayout = new javax.swing.GroupLayout(panel_doanhthu);
        panel_doanhthu.setLayout(panel_doanhthuLayout);
        panel_doanhthuLayout.setHorizontalGroup(
            panel_doanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_doanhthuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_doanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_doanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbl_shownewkhachhangtoday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_showdoanhthutoday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_doanhthu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                    .addComponent(lbl_khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(panel_doanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_hoadon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_hoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_showhoadontoday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_countsanphamtoday, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        panel_doanhthuLayout.setVerticalGroup(
            panel_doanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_doanhthuLayout.createSequentialGroup()
                .addGroup(panel_doanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_doanhthu)
                    .addComponent(lbl_hoadon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_doanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_showdoanhthutoday)
                    .addComponent(lbl_showhoadontoday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_doanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_khachhang)
                    .addComponent(lbl_hoadon1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_doanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_shownewkhachhangtoday)
                    .addComponent(lbl_countsanphamtoday))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_doanhthu1.setBackground(new java.awt.Color(204, 204, 255));
        panel_doanhthu1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doanh Thu Tháng Này", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        lbl_doanhthu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_doanhthu1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_doanhthu1.setText("Doanh Thu Tháng Này");

        lbl_showdoanhthuthismonth.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_showdoanhthuthismonth.setText("1,300,000 VNĐ");

        lbl_hoadon2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_hoadon2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_hoadon2.setText("Số Hóa Đơn");

        lbl_showhoadonthismonth.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_showhoadonthismonth.setText("10");

        lbl_khachhang1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_khachhang1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_khachhang1.setText("Số Khách Hàng Mới");

        lbl_shownewkhachhangthismonth.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_shownewkhachhangthismonth.setText("10");

        lbl_hoadon3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_hoadon3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_hoadon3.setText("Số Lượng Sản Phẩm Bán Ra");

        lbl_countsanphamthismonth.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_countsanphamthismonth.setText("10");

        btn_openchart.setText("Biểu Đồ");
        btn_openchart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openchartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_doanhthu1Layout = new javax.swing.GroupLayout(panel_doanhthu1);
        panel_doanhthu1.setLayout(panel_doanhthu1Layout);
        panel_doanhthu1Layout.setHorizontalGroup(
            panel_doanhthu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_doanhthu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_doanhthu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_doanhthu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbl_shownewkhachhangthismonth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_showdoanhthuthismonth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_doanhthu1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                    .addComponent(lbl_khachhang1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(panel_doanhthu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_hoadon3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_hoadon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_showhoadonthismonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_countsanphamthismonth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
            .addGroup(panel_doanhthu1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(btn_openchart, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_doanhthu1Layout.setVerticalGroup(
            panel_doanhthu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_doanhthu1Layout.createSequentialGroup()
                .addGroup(panel_doanhthu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_doanhthu1)
                    .addComponent(lbl_hoadon2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_doanhthu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_showdoanhthuthismonth)
                    .addComponent(lbl_showhoadonthismonth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_doanhthu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_khachhang1)
                    .addComponent(lbl_hoadon3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_doanhthu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_shownewkhachhangthismonth)
                    .addComponent(lbl_countsanphamthismonth))
                .addGap(18, 18, 18)
                .addComponent(btn_openchart)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panel_lshd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbl_hoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã HĐ", "Tên Khách Hàng", "Thành Tiền", "Ngày Tạo", "Ngày Thanh Toán"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_hoadon);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Ngày bắt đầu :");

        datestart.setDateFormatString("dd-MM-yyyy");
        datestart.setMaxSelectableDate(new java.util.Date(253370743316000L));
        datestart.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                datestartHierarchyChanged(evt);
            }
        });
        datestart.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datestartPropertyChange(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Ngày kết thúc :");

        dateend.setDateFormatString("dd-MM-yyyy");
        dateend.setMaxSelectableDate(new java.util.Date(253370743316000L));
        dateend.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                dateendHierarchyChanged(evt);
            }
        });
        dateend.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateendPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout panel_lshdLayout = new javax.swing.GroupLayout(panel_lshd);
        panel_lshd.setLayout(panel_lshdLayout);
        panel_lshdLayout.setHorizontalGroup(
            panel_lshdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_lshdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datestart, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dateend, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panel_lshdLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_lshdLayout.setVerticalGroup(
            panel_lshdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_lshdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_lshdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(datestart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(dateend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOP 5 Nhân Viên Doanh Số Cao Nhất Tháng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbl_nhanvien1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã Nhân Viên", "Họ Và Tên", "Doanh Số"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_nhanvien1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOP 5 Khách Hàng Tiềm Năng Nhất Tháng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbl_khachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã Khách Hàng", "Họ Và Tên", "Tổng Chi Tiêu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbl_khachhang);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_lshd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_doanhthu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_doanhthu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_doanhthu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_doanhthu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_lshd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_openchartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openchartActionPerformed
        new View_Chart().setVisible(true);
    }//GEN-LAST:event_btn_openchartActionPerformed

    private void datestartHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_datestartHierarchyChanged

    }//GEN-LAST:event_datestartHierarchyChanged

    private void datestartPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datestartPropertyChange
        if (datestart.getDate() != null) {
            filltblhd();
        }
    }//GEN-LAST:event_datestartPropertyChange

    private void dateendHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_dateendHierarchyChanged

    }//GEN-LAST:event_dateendHierarchyChanged

    private void dateendPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateendPropertyChange
        if (dateend.getDate() != null) {
            filltblhd();
        }
    }//GEN-LAST:event_dateendPropertyChange

    private void filltbltop5nv() {
        DefaultTableModel model = (DefaultTableModel) tbl_nhanvien1.getModel();
        model.setRowCount(0);
        for (Vector<Object> ob : thongke.gettop5nv()) {
            model.addRow(ob);
        }
    }

    private void filltbltop5kh() {
        DefaultTableModel model = (DefaultTableModel) tbl_khachhang.getModel();
        model.setRowCount(0);
        for (Vector<Object> ob : thongke.gettop5kh()) {
            model.addRow(ob);
        }
    }

    private void filltblhd() {
        DefaultTableModel model = (DefaultTableModel) tbl_hoadon.getModel();
        model.setRowCount(0);
        try {
            Date start = datestart.getDate();
            Date end = dateend.getDate();
            for (Vector<Object> ob : thongke.getHoadon(start, end)) {
                model.addRow(ob);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_openchart;
    private com.toedter.calendar.JDateChooser dateend;
    private com.toedter.calendar.JDateChooser datestart;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_countsanphamthismonth;
    private javax.swing.JLabel lbl_countsanphamtoday;
    private javax.swing.JLabel lbl_doanhthu;
    private javax.swing.JLabel lbl_doanhthu1;
    private javax.swing.JLabel lbl_hoadon;
    private javax.swing.JLabel lbl_hoadon1;
    private javax.swing.JLabel lbl_hoadon2;
    private javax.swing.JLabel lbl_hoadon3;
    private javax.swing.JLabel lbl_khachhang;
    private javax.swing.JLabel lbl_khachhang1;
    private javax.swing.JLabel lbl_showdoanhthuthismonth;
    private javax.swing.JLabel lbl_showdoanhthutoday;
    private javax.swing.JLabel lbl_showhoadonthismonth;
    private javax.swing.JLabel lbl_showhoadontoday;
    private javax.swing.JLabel lbl_shownewkhachhangthismonth;
    private javax.swing.JLabel lbl_shownewkhachhangtoday;
    private javax.swing.JPanel panel_doanhthu;
    private javax.swing.JPanel panel_doanhthu1;
    private javax.swing.JPanel panel_lshd;
    private javax.swing.JTable tbl_hoadon;
    private javax.swing.JTable tbl_khachhang;
    private javax.swing.JTable tbl_nhanvien;
    private javax.swing.JTable tbl_nhanvien1;
    // End of variables declaration//GEN-END:variables

    private void inits() {
        String dthutoday = XuLyString.formatTien(thongke.getDoanhThuToday());
        String dthuthismonth = XuLyString.formatTien(thongke.getDoanhThuThisMonth());
        lbl_showdoanhthutoday.setText(dthutoday);
        lbl_showdoanhthuthismonth.setText(dthuthismonth);
        lbl_countsanphamtoday.setText(String.valueOf(thongke.gettotalsptoday()));
        lbl_countsanphamthismonth.setText(String.valueOf(thongke.gettotalspthismonth()));
        lbl_showhoadontoday.setText(String.valueOf(thongke.gettotalsptoday()));
        lbl_showhoadontoday.setText(String.valueOf(thongke.gettotalspthismonth()));
        lbl_shownewkhachhangthismonth.setText(String.valueOf(thongke.gettotalcustomersthismonth()));
        lbl_shownewkhachhangtoday.setText(String.valueOf(thongke.gettotalcustomerstoday()));
        filltbltop5nv();
        filltbltop5kh();
        filltblhd();
    }
}
