CREATE DATABASE ERD_Group4_SD18309 
GO 
USE ERD_Group4_SD18309 
GO

CREATE TABLE ThuongHieu (
	ID_ThuongHieu INT IDENTITY PRIMARY KEY NOT NULL,
	Ten_ThuongHieu NVARCHAR(256) NOT NULL
)

CREATE TABLE Mau (
	ID_Mau INT IDENTITY PRIMARY KEY NOT NULL,
	Ten_Mau NVARCHAR(256) NOT NULL
)

CREATE TABLE Size (
	ID_Size INT IDENTITY PRIMARY KEY NOT NULL,
	Ten_Size NVARCHAR(256) NOT NULL
)

CREATE TABLE ChatLieu (
	ID_ChatLieu INT IDENTITY PRIMARY KEY NOT NULL,
	Ten_ChatLieu NVARCHAR(256) NOT NULL
)

CREATE TABLE SanPham (
	ID_SanPham INT IDENTITY PRIMARY KEY NOT NULL,
	Ma_SanPham INT NOT NULL,
	Ten_SanPham NVARCHAR(256) NOT NULL,
	MoTa_SanPham NVARCHAR(500) NOT NULL,
	TrangThai_SanPham NVARCHAR(100) NOT NULL
)

CREATE TABLE ChucVu (
	ID_ChucVu INT IDENTITY PRIMARY KEY NOT NULL,
	Ten_ChucVu NVARCHAR(100) NOT NULL
)

CREATE TABLE NhanVien (
	ID_NhanVien INT IDENTITY PRIMARY KEY NOT NULL,
	Ten_NhanVien NVARCHAR(256) NOT NULL,
	CCCD_NhanVien BIGINT NOT NULL,
	Email_NhanVien VARCHAR(200) NOT NULL,
	Sdt_NhanVien INT NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh NVARCHAR(10) NOT NULL,
	DiaChi NVARCHAR (256) NOT NULL,
	ID_ChucVu INT FOREIGN KEY REFERENCES ChucVu(ID_ChucVu),
	TrangThai_NhanVien NVARCHAR(100) NOT NULL
)

CREATE TABLE DotGiamGia (
	ID_DotGiamGia INT IDENTITY PRIMARY KEY NOT NULL,
	Ma_DotGiamGia INT NOT NULL,
	Ten_DotGiamGia NVARCHAR(256) NOT NULL,
	NgayBatDau_DotGiamGia DATE NOT NULL,
	NgayKetThuc_DotGiamGia DATE NOT NULL,
	GiaTri_DotGiamGia DECIMAL(5, 2) NOT NULL,
	DieuKien_DotGiamGia NVARCHAR(MAX) NOT NULL,
	GiamToiDa_DotGiamGia FLOAT NOT NULL,
	GiamTheo_DotGiamGia NVARCHAR(MAX) NOT NULL,
	ID_NhanVien INT FOREIGN KEY REFERENCES NhanVien(ID_NhanVien),
	TrangThai_DotGiamGia NVARCHAR(100) NOT NULL
)

CREATE TABLE SanPham_ChiTiet (
	ID_SanPhamChiTiet INT IDENTITY PRIMARY KEY NOT NULL,
	GiaNiemYet_SanPhamChiTiet FLOAT NOT NULL,
	SoLuong_SanPhamChiTiet INT NOT NULL,
	ID_ThuongHieu INT  FOREIGN KEY REFERENCES ThuongHieu (ID_ThuongHieu),
	ID_Mau INT  FOREIGN KEY REFERENCES Mau (ID_Mau),
	ID_ChatLieu INT FOREIGN KEY REFERENCES ChatLieu(ID_ChatLieu),
	ID_SanPham INT FOREIGN KEY REFERENCES SanPham(ID_SanPham),
	Anh_SanPhamChiTiet VARCHAR(256) NOT NULL,
	ID_NhanVien INT FOREIGN KEY REFERENCES NhanVien(ID_NhanVien),
	ID_DotGiamGia INT FOREIGN KEY REFERENCES DotGiamGia(ID_DotGiamGia),
	TrangThai_SanPhamChiTiet NVARCHAR(100) NOT NULL
)



CREATE TABLE PhieuGiamGia (
	ID_PhieuGiamGia INT IDENTITY PRIMARY KEY NOT NULL,
	Ma_PhieuGiamGia INT NOT NULL,
	MucGiam_PhieuGiamGia FLOAT NOT NULL,
	GiamTheo_PhieuGiamGia NVARCHAR(MAX) NOT NULL,
	DieuKien_PhieuGiamGia NVARCHAR(MAX) NOT NULL,
	SoPhieuPhatHanh_PhieuGiamGia INT NOT NULL,
	NgayBatDau_PhieuGiamGia DATE NOT NULL,
	NgayKetThuc_PhieuGiamGia DATE NOT NULL,
	MoTa_PhieuGiamGia NVARCHAR(MAX) NOT NULL,
	ID_NhanVien INT FOREIGN KEY REFERENCES NhanVien(ID_NhanVien),
	TrangThai_PhieuGiamGia NVARCHAR(100) NOT NULL
)

CREATE TABLE XepHang (
	ID_XepHang INT IDENTITY PRIMARY KEY NOT NULL,
	Ten_XepHang NVARCHAR(256) NOT NULL
)

CREATE TABLE KhachHang (
	ID_KhachHang INT IDENTITY PRIMARY KEY NOT NULL,
	Ma_KhachHang INT NOT NULL,
	HoVaTen_KhachHang NVARCHAR(100) NOT NULL,
	NgaySinh_KhachHang DATE NOT NULL,
	SDT_KhachHang INT NOT NULL,
	Email_KhachHang VARCHAR(256) NOT NULL,
	Diem_KhachHang INT NOT NULL,
	ID_XepHang INT FOREIGN KEY REFERENCES XepHang(ID_XepHang),
	ID_DotGiamGia INT FOREIGN KEY REFERENCES DotGiamGia(ID_DotGiamGia),
	NhomKhachHang_KhachHang NVARCHAR(256) NOT NULL,
	ID_NhanVien INT FOREIGN KEY REFERENCES NhanVien(ID_NhanVien),
	TrangThai_KhachHang NVARCHAR(100) NOT NULL
)

CREATE TABLE HoaDon (
	ID_HoaDon INT IDENTITY PRIMARY KEY NOT NULL,
	Ma_HoaDon INT NOT NULL,
	ID_NhanVien INT FOREIGN KEY REFERENCES NhanVien(ID_NhanVien),
	ID_KhachHang INT FOREIGN KEY REFERENCES KhachHang(ID_KhachHang),
	PhuongThucThanhToan_HoaDon NVARCHAR(256) NOT NULL,
	NgayTao_HoaDon DATE NOT NULL,
	TongTien_HoaDon FLOAT NOT NULL,
	TienKhachTra FLOAT NOT NULL,
	TienThua FLOAT NOT NULL,
	ID_PhieuGiamGia INT FOREIGN KEY REFERENCES PhieuGiamGia(ID_PhieuGiamGia),
	ID_DotGiamGia INT FOREIGN KEY REFERENCES DotGiamGia(ID_DotGiamGia),
	TrangThai_HoaDon NVARCHAR(100) NOT NULL
)

CREATE TABLE HoaDon_ChiTiet (
	ID_HoaDonChiTiet INT IDENTITY PRIMARY KEY NOT NULL,
	ID_HoaDon INT FOREIGN KEY REFERENCES HoaDon(ID_HoaDon),
	ID_SanPhamChiTiet INT FOREIGN KEY REFERENCES SanPham_ChiTiet(ID_SanPhamChiTiet),
	SoLuong_HoaDonChiTiet INT NOT NULL,
	DonGia FLOAT NOT NULL,
	ThanhTien FLOAT NOT NULL
)

CREATE TABLE PhieuGiaoHang (
	ID_PhieuGiao INT IDENTITY PRIMARY KEY NOT NULL,
	ID_NhanVien INT FOREIGN KEY REFERENCES NhanVien(ID_NhanVien),
	ID_KhachHang INT FOREIGN KEY REFERENCES KhachHang(ID_KhachHang),
	Ten_GiaoHang NVARCHAR(256) NOT NULL,
	SDT_GiaoHang INT NOT NULL,
	DiaChi_GiaoHang NVARCHAR(256) NOT NULL,
	GiaShip_GiaoHang FLOAT NOT NULL,
	NgayTao_GiaoHang DATE NOT NULL,
	TrangThai_GiaoHang NVARCHAR(100) NOT NULL
)

CREATE TABLE PhieuGiao_SanPham (
	ID_PhieuGiao_SanPham INT IDENTITY PRIMARY KEY NOT NULL,
	ID_SanPhamChiTiet INT FOREIGN KEY REFERENCES SanPham_ChiTiet(ID_SanPhamChiTiet),
	ID_PhieuGiao INT FOREIGN KEY REFERENCES PhieuGiaoHang (ID_PhieuGiao)
)

CREATE TABLE LichSuMuaHang (
	ID_LichSu INT IDENTITY PRIMARY KEY NOT NULL,
	ID_KhachHang INT FOREIGN KEY REFERENCES KhachHang(ID_KhachHang),
	ID_HoaDon INT FOREIGN KEY REFERENCES HoaDon(ID_HoaDon),
	ID_SanPhamChiTiet INT FOREIGN KEY REFERENCES SanPham_ChiTiet(ID_SanPhamChiTiet)
)

CREATE TABLE KhachHang_PhieuGiamGia (
	ID_KhachHang INT NOT NULL,
	ID_PhieuGiamGia INT NOT NULL,
	FOREIGN KEY (ID_KhachHang) REFERENCES KhachHang(ID_KhachHang),
    FOREIGN KEY (ID_PhieuGiamGia) REFERENCES  PhieuGiamGia(ID_PhieuGiamGia)
)

CREATE TABLE DotGiamGia_HoaDon (
	ID_DotGiamGia INT FOREIGN KEY REFERENCES DotGiamGia(ID_DotGiamGia),
	ID_HoaDon INT FOREIGN KEY REFERENCES HoaDon(ID_HoaDon)
)

CREATE TABLE TaiKhoan (
	ID_TaiKhoan INT IDENTITY PRIMARY KEY NOT NULL,
	TenDangNhap VARCHAR(100) NOT NULL,
	MatKhau VARCHAR(100) NOT NULL,
	ID_NhanVien INT FOREIGN KEY REFERENCES NhanVien(ID_NhanVien),
	ROLE VARCHAR(50) NOT NULL,
	TrangThai_TaiKhoan NVARCHAR(100) NOT NULL
)